name: Build Electron APP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-app:
    runs-on: windows-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [18.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.14.0

      - name: Install Dependencies
        run: pnpm install

      - name: Build Genshin Helper
        run: pnpm run make

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: GenshinHelper_${{ matrix.os }}
          path: ./out/make/*
